samples:
  # 044N_v14: /data1/greenbab/projects/methyl_benchmark_spectrum/data/preprocessed/sup_5mCG_5hmCG/results/mark_duplicates/044N_v14/044N_v14_modBaseCalls_sorted_dup.bam
  D01_4000: /data1/greenbab/projects/triplicates_epigenetics_diyva/DNA/preprocessed/D-0-1_4000_haplotagged_5mCcoPhased_Authorscomment.bam

  # Add more samples as `name: /path/to/sample.bam`

##### reference genomes
# set_species: "hg38"
# ref: /data1/greenbab/database/hg38/v0/Homo_sapiens_assembly38.fasta
# regions: /data1/greenbab/database/CpGIslands/hg38_chr14_CpGIslands.bed
# hg38_chrSizes: /data1/greenbab/database/sizes.Homo_sapiens_assembly38

set_species: "mm10"
ref: /data1/greenbab/database/mm10/mm10.fa
regions: /data1/greenbab/database/mm10/mm10_chr14_CpGIslands.bed

# --include-bed


workdir: /data1/greenbab/users/ahunos/apps/workflows/methylation_workflows/modkit_wf

#Entropy configs
modkit_entropyMotifs: "--motif CG 0"
# modkit_entropy_extraArgs: "--combine-strands"
# modkit_entropy_extraArgs: "--combine-strands 4 --window-size 50"

##modkit pileup
pileupRegion: chr19
# pileupBedgraph: True

# mm10: /data1/greenbab/database/mm10/mm10.fa
# ref: /data1/greenbab/database/hg38/v0/Homo_sapiens_assembly38.fasta
# mm10_chrSizes: /data1/greenbab/database/mm10/mm10.chrom.sizes


#processing
threads: 32
